%
% AE508 Optimal Space Trajectories, Spring 2025
% Course Project
% 
% Peter Nalyvayko (petern4@illinois.edu)
% Maximize the velocity of the spacecraft at the time of intercept

clearvars; close all; clc;
format longg;
addpath(".");

function err = maxFinalVelocity(lam0guess,t0,tf,x0,xf,T,c,rho,opts_ode,m0,mu)
    [t, X] = ode45(@eom, [t0 tf], [x0; m0; lam0guess(1:7)],opts_ode,T,c,rho,mu);
    % See my notes, page 120, boundary conditions
    % The mass at the final time is free
    err = [X(end,1:3)' - xf(1:3); X(end,11:13)' + 1; X(end,14)];
end


state_values = init();
state_values.tf = 429250.237098388; % time of flight, in seconds

% Reduce the thrust magnitude in attempt to converge to a solution
% state_values.T = state_values.T * 0.1;

% Solve the Lambert's equation analytically
[v1,v2] = lambert( ...
    state_values.r0, ...
    state_values.rf, ...
    state_values.tf, ...
    state_values.mu, ...
    'pro');

% x0 = [state_values.r0;v1];
x0 = [state_values.r0;state_values.v0];
xf = [state_values.rf;state_values.vf];

rho = 1.0;
%
opts_ode = odeset('RelTol',1e-13,'AbsTol',1e-15); % ode
options = optimoptions('fsolve','Display','iter','MaxFunEvals',2e3,...
    'MaxIter',2e3,'TolFun',1e-12,'TolX',1e-14,...
    'UseParallel',false);
%
% Solve optimal trajectory problem by maximizing the velocity a
% the time of intercept.
%
lam_guess = 1e-5*ones(7,1);
[p0,~] = fsolve(@maxFinalVelocity, ...
    lam_guess, ...
    options, ...
    state_values.t0, ...
    state_values.tf, ...
    x0, ...
    xf, ...
    state_values.T, ...
    state_values.c, ...
    rho, ...
    opts_ode, ...
    state_values.m0, ...
    state_values.mu);
[t, X] = ode45(@eom, [state_values.t0 state_values.tf], ...
    [x0; state_values.m0; p0(1:7)], ...
    opts_ode, ...
    state_values.T, ...
    state_values.c, ...
    rho, ...
    state_values.mu);

% The terminal constraint
dr = X(end,1:3)' - state_values.rf

if norm(dr) < 1e-3
    H = hamiltonian(t,X, ...
        state_values.T, ...
        state_values.c, ...
        rho, ...
        state_values.mu);
    %
    % Plot the Hamiltonian
    %
    plot(t, H, 'LineWidth', 1.5);
    % Plot the states, costates, control and the optimal trajectory
    plots(t,X,state_values.r0,state_values.rf,state_values.mu);
else
    fprintf("The position at t=0: r0 = %.3f, %.3f, %.3f, norm=%.6f\n", ...
        state_values.r0(1), ...
        state_values.r0(2), ...
        state_values.r0(3), ...
        norm(state_values.r0));
    fprintf("The position at t=tf: r0 = %.3f, %.3f, %.3f, norm=%.6f\n", ...
        state_values.rf(1), ...
        state_values.rf(2), ...
        state_values.rf(3), ...
        norm(state_values.rf));
    fprintf("The solution didnt converge, dr=%.6f\n", norm(dr));
end
